name: sn17-gen-v2

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - torchvision=0.19.0
  - pip
  - pip:
      - fastapi==0.115.0
      - uvicorn[standard]==0.30.6
      - loguru==0.7.2
      - diffusers==0.30.0
      - transformers==4.44.2
      - accelerate==0.34.2
      - xformers==0.0.27.post2
      - httpx==0.27.2
      - pillow==10.4.0
      - numpy==2.0.2
      - omegaconf==2.3.0
      - einops==0.7.0
      - git+https://github.com/tatsy/torchmcubes.git
      - trimesh==4.0.5
      - huggingface-hub
      - imageio[ffmpeg]
      - xatlas==0.0.9
      - moderngl==5.10.0
